import os

MAX_CONTEXT_WINDOW = 8000
SECOND_WATER_LEVEL = float(os.getenv("SHORT_MEM_SECOND_WATER_LEVEL", "0.5"))
LONG_MEM_N = 5

CHUNK_THRESHOLD = int(os.getenv("LONG_MEM_CHUNK_THRESHOLD", "500"))
CHUNK_MAX_CHARS = int(os.getenv("LONG_MEM_CHUNK_MAX_CHARS", "1500"))
CHUNK_OVERLAP = int(os.getenv("LONG_MEM_CHUNK_OVERLAP", "200"))
CHUNK_SEARCH_MULTIPLIER = int(os.getenv("LONG_MEM_CHUNK_SEARCH_MULTIPLIER", "3"))